version: "3"

services:

  contasdb:
    image: postgres:13-alpine
    container_name: contasdb
    restart: always
    networks: 
      - backendcontas
    environment:
      - POSTGRES_DB=${CONTAS_DB_NAME}
      - POSTGRES_USER=${CONTAS_DB_USER}
      - POSTGRES_PASSWORD=${CONTAS_DB_PASS}
      - POSTGRES_PORT=${CONTAS_DB_PORT}
    expose:
      - "${CONTAS_DB_PORT}"
    ports:
      - "${CONTAS_DB_PORT}:${CONTAS_DB_PORT}"
      

  transacoesdb:
    image: postgres:13-alpine
    container_name: transacoesdb
    restart: always
    networks: 
      - backendtransacoes
    environment:
      - POSTGRES_DB=${TRANSACOES_DB_NAME}
      - POSTGRES_USER=${TRANSACOES_DB_USER}
      - POSTGRES_PASSWORD=${TRANSACOES_DB_PASS}
      - POSTGRES_PORT=${TRANSACOES_DB_PORT}
    expose:
      - "${TRANSACOES_DB_PORT}"
    ports:
      - "${TRANSACOES_DB_PORT}:${TRANSACOES_DB_PORT}"
      
  
  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: conta-rabbitmq
    restart: always
    hostname: rabbitmq
    networks: 
      - rabbit
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./.rabbitmq_data:/var/lib/rabbitmq/mnesia"

  contasapp:
    build: ./contas
    container_name: contasapp
    entrypoint: ./.docker/entrypoint.sh
    command: ["yarn", "dev"]
    environment:
      APPCONTAS_PORT: ${APPCONTAS_PORT}
      CONTAS_DB_NAME: ${CONTAS_DB_NAME}
      CONTAS_DB_USER: ${CONTAS_DB_USER}
      CONTAS_DB_PASS: ${CONTAS_DB_PASS}
      CONTAS_DB_PORT: ${CONTAS_DB_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_URI: ${RABBITMQ_URI}
    restart: always
    ports:
      - "${APPCONTAS_PORT}:${APPCONTAS_PORT}"
    links:
      - contasdb
    networks: 
      - backendcontas
      - rabbit
    volumes:
      - ./contas:/home/node/contas
    depends_on:
      - contasdb
      - rabbitmq

  transacoesapp:
    build: ./transacoes
    container_name: transacoesapp
    entrypoint: ./.docker/entrypoint.sh
    command: ["yarn", "dev"]
    environment:
      APPTRANSACAO_PORT: ${APPTRANSACAO_PORT}
      TRANSACOES_DB_NAME: ${TRANSACOES_DB_NAME}
      TRANSACOES_DB_USER: ${TRANSACOES_DB_USER}
      TRANSACOES_DB_PASS: ${TRANSACOES_DB_PASS}
      TRANSACOES_DB_PORT: ${TRANSACOES_DB_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_URI: ${RABBITMQ_URI}
    restart: always
    ports:
      - "${APPTRANSACAO_PORT}:${APPTRANSACAO_PORT}"
    links:
      - transacoesdb
    networks: 
      - backendtransacoes
      - rabbit
    volumes:
      - ./transacoes:/home/node/transacoes
    depends_on:
      - transacoesdb
      - rabbitmq

networks:
  backendcontas:
    driver: bridge
  backendtransacoes:
    driver: bridge
  rabbit:
    driver: bridge