version: "3"

services:

  db:
    image: postgres:13-alpine
    container_name: contas-db
    restart: always
    environment:
      - POSTGRES_DB=${CONTAS_DB_NAME}
      - POSTGRES_USER=${CONTAS_DB_USER}
      - POSTGRES_PASSWORD=${CONTAS_DB_PASS}
    expose:
      - "${CONTAS_DB_PORT}"
    ports:
      - "${CONTAS_DB_PORT}:5435"
      

  db2:
    image: postgres:13-alpine
    container_name: transacoes-db
    restart: always
    environment:
      - POSTGRES_DB=${TRANSACOES_DB_NAME}
      - POSTGRES_USER=${TRANSACOES_DB_USER}
      - POSTGRES_PASSWORD=${TRANSACOES_DB_PASS}
    expose:
      - "${TRANSACOES_DB_PORT}"
    ports:
      - "${TRANSACOES_DB_PORT}:5436"
      
  
  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: conta-rabbitmq
    restart: always
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./.rabbitmq_data:/var/lib/rabbitmq/mnesia"