services:

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      # - POSTGRES_DB="${postgres}"
      # - POSTGRES_USER="${POSTGRES_USER}"
      # - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"

      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    expose:
    - "5432" 
    ports:
      - "8001:5432"
      